name: Project Runner

on:
  push:
    branches:
      - main

jobs: 
  run_script:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
          
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
            path: "Requierments.txt"

      - name: execute main
        run: |
          python Main.py
          git config --local user.email "aminachak8182@gmail.com"
          git config --local user.name "Clancyov"
          git add -A
          git status
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: List files in directory
        id: list-files
        run: |
          files=$(find Outputs/Phones/Images -type f)
          echo "::set-output name=files::$files"
          
      - name: Telegram Actions
        uses: appleboy/telegram-action@master
        with:
             to: ${{ secrets.CHAT_ID }}
             token: ${{ secrets.TELEGRAM_TOKEN }}
             message: test
             # photo: Outputs/Phones/Images/samsung0.png
             # document: Outputs/Phones/Images/samsung0.png
             files: ${{ steps.list-files.outputs.files }}

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSHER_TOKEN }}
          branch: main 
