name: Project Runner

on:
  push:
    branches:
      - main

jobs: 
  run_script:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
          
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
            path: "Requierments.txt"

      - name: execute main
        run: |
          python Main.py
          git config --local user.email "aminachak8182@gmail.com"
          git config --local user.name "Clancyov"
          git add -A
          git status
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)
          
      # - name: Telegram Actions
      #   uses: appleboy/telegram-action@master
      #   with:
      #        to: ${{ secrets.CHAT_ID }}
      #        token: ${{ secrets.TELEGRAM_TOKEN }}
      #        message: test
      #        document: Outputs/Phones/Images/samsung0.png

      # - name: Telegram Actions
      #   uses: appleboy/telegram-action@master
      #   with:
      #        to: ${{ secrets.CHAT_ID }}
      #        token: ${{ secrets.TELEGRAM_TOKEN }}
      #        message: test
      #        document: Outputs/Phones/Images/samsung1.png

      - name: install telegram dependencys
        run:
          pip install python-telegram-bot
          
      - name: Run Python script
        run: python EXPERIMENTS/Telegram/Send_with_telegram.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Assuming you have a Telegram token secret
          CHAT_ID: ${{ secrets.CHAT_ID }}  # Add any other secrets needed by your script

        
      - name: Delete file
        run: rm example.txt
        
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PUSHER_TOKEN }}
          branch: main 
